{% set name = "red-black-tree-mod" %}
{% set version = "1.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/red-black-tree-mod-{{ version }}.tar.gz
  sha256: 38e3652903a2bf96379c27c2082ca0b7b905158662dd7ef0c97f4fd93a9aa908

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - red_black_dict_mod
    - red_black_set_mod
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://stromberg.dnsalias.org/~strombrg/red-black-tree-mod/
  summary: Flexible python implementation of red black trees
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - jan-janssen
